# Generated by Django 4.2.10 on 2024-02-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
