# Generated by Django 4.2.10 on 2024-02-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='answer',
        ),
    ]
