# Generated by Django 4.2.10 on 2024-02-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_rename_question_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question',
        ),
    ]
